version: '3'
services:
  min-cassandra:
    image: cassandra:latest
    volumes:
      - ${PWD}/etc/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ${PWD}/etc/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
